# Generated by Django 2.2.7 on 2020-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='happy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='imglnk',
            field=models.CharField(default='', max_length=250),
        ),
    ]
