# Generated by Django 2.2.7 on 2020-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200710_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='faces',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
